import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import en_GB from "antd/lib/locale/en_GB";
import moment from "moment";
import "moment/locale/en-gb"; // important!

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

moment.updateLocale("en_GB", {
  weekdaysMin: ["Mon", "Tue", "Wed", "Thu", "Sat", "Fri", "Sun"], // Thứ tự tùy chỉnh
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider locale={en_GB}>
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
